<?xml version = "1.0" ?>
<?xml:stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW ADC_channels CDATA #IMPLIED>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Code_IPC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEDEC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEITA CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink3Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink3URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink4Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink4URL CDATA #IMPLIED>
  <!ATTLIST ROW CompType CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetDocument CDATA #IMPLIED>
  <!ATTLIST ROW DatasheetVersion CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW DrillSize CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Flash CDATA #IMPLIED>
  <!ATTLIST ROW fmax CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW GPIOs CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW High_Reliability CDATA #IMPLIED>
  <!ATTLIST ROW I2C CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionDate CDATA #IMPLIED>
  <!ATTLIST ROW LatestRevisionNote CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Model_Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Model_Simulation CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW Note CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PackageDescription CDATA #IMPLIED>
  <!ATTLIST ROW PackageDocument CDATA #IMPLIED>
  <!ATTLIST ROW PackageReference CDATA #IMPLIED>
  <!ATTLIST ROW PackageTopMarking CDATA #IMPLIED>
  <!ATTLIST ROW PackageVersion CDATA #IMPLIED>
  <!ATTLIST ROW PartNumber CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW PinCount CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW PLL CDATA #IMPLIED>
  <!ATTLIST ROW PowerWise CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Published CDATA #IMPLIED>
  <!ATTLIST ROW Publisher CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW RoHS CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW SPI CDATA #IMPLIED>
  <!ATTLIST ROW SRAM CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Timers CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW UART CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Value CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
  <!ATTLIST ROW VDD__max_ CDATA #IMPLIED>
  <!ATTLIST ROW VDD__min_ CDATA #IMPLIED>
  <!ATTLIST ROW VDD__typ_ CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="ADC_channels" Caption="ADC channels" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address1" Caption="Address1" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="Code_IPC" Caption="Code_IPC" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Code_JEDEC" Caption="Code_JEDEC" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Code_JEITA" Caption="Code_JEITA" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description" Caption="ComponentLink1Description" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL" Caption="ComponentLink1URL" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description" Caption="ComponentLink2Description" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL" Caption="ComponentLink2URL" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink3Description" Caption="ComponentLink3Description" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink3URL" Caption="ComponentLink3URL" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink4Description" Caption="ComponentLink4Description" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink4URL" Caption="ComponentLink4URL" Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="CompType" Caption="CompType" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="DatasheetDocument" Caption="DatasheetDocument" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="DatasheetVersion" Caption="DatasheetVersion" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="DrillSize" Caption="DrillSize" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="Flash" Caption="Flash" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="fmax" Caption="fmax" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="GPIOs" Caption="GPIOs" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="High_Reliability" Caption="High-Reliability" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="I2C" Caption="I2C" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionDate" Caption="LatestRevisionDate" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="LatestRevisionNote" Caption="LatestRevisionNote" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer" Caption="Manufacturer" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="Model_Signal_Integrity" Caption="Model:Signal Integrity" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="Model_Simulation" Caption="Model:Simulation" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="Note" Caption="Note" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="PackageDescription" Caption="PackageDescription" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="PackageDocument" Caption="PackageDocument" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="PackageReference" Caption="PackageReference" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="PackageTopMarking" Caption="PackageTopMarking" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="PackageVersion" Caption="PackageVersion" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="PartNumber" Caption="PartNumber" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="PinCount" Caption="PinCount" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
    <COLUMN Name="PLL" Caption="PLL" Index="79" BandIndex="0" RowIndex="0" ColIndex="79" Width="100"></COLUMN>
    <COLUMN Name="PowerWise" Caption="PowerWise" Index="80" BandIndex="0" RowIndex="0" ColIndex="80" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="81" BandIndex="0" RowIndex="0" ColIndex="81" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="82" BandIndex="0" RowIndex="0" ColIndex="82" Width="100"></COLUMN>
    <COLUMN Name="Published" Caption="Published" Index="83" BandIndex="0" RowIndex="0" ColIndex="83" Width="100"></COLUMN>
    <COLUMN Name="Publisher" Caption="Publisher" Index="84" BandIndex="0" RowIndex="0" ColIndex="84" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="85" BandIndex="0" RowIndex="0" ColIndex="85" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="86" BandIndex="0" RowIndex="0" ColIndex="86" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="87" BandIndex="0" RowIndex="0" ColIndex="87" Width="100"></COLUMN>
    <COLUMN Name="RoHS" Caption="RoHS" Index="88" BandIndex="0" RowIndex="0" ColIndex="88" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="89" BandIndex="0" RowIndex="0" ColIndex="89" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="90" BandIndex="0" RowIndex="0" ColIndex="90" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="91" BandIndex="0" RowIndex="0" ColIndex="91" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="92" BandIndex="0" RowIndex="0" ColIndex="92" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="93" BandIndex="0" RowIndex="0" ColIndex="93" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="94" BandIndex="0" RowIndex="0" ColIndex="94" Width="100"></COLUMN>
    <COLUMN Name="SPI" Caption="SPI" Index="95" BandIndex="0" RowIndex="0" ColIndex="95" Width="100"></COLUMN>
    <COLUMN Name="SRAM" Caption="SRAM" Index="96" BandIndex="0" RowIndex="0" ColIndex="96" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="97" BandIndex="0" RowIndex="0" ColIndex="97" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="98" BandIndex="0" RowIndex="0" ColIndex="98" Width="100"></COLUMN>
    <COLUMN Name="Timers" Caption="Timers" Index="99" BandIndex="0" RowIndex="0" ColIndex="99" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="100" BandIndex="0" RowIndex="0" ColIndex="100" Width="100"></COLUMN>
    <COLUMN Name="UART" Caption="UART" Index="101" BandIndex="0" RowIndex="0" ColIndex="101" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="102" BandIndex="0" RowIndex="0" ColIndex="102" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="103" BandIndex="0" RowIndex="0" ColIndex="103" Width="100"></COLUMN>
    <COLUMN Name="Value" Caption="Value" Index="104" BandIndex="0" RowIndex="0" ColIndex="104" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="105" BandIndex="0" RowIndex="0" ColIndex="105" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="106" BandIndex="0" RowIndex="0" ColIndex="106" Width="100"></COLUMN>
    <COLUMN Name="VDD__max_" Caption="VDD &#40;max&#41;" Index="107" BandIndex="0" RowIndex="0" ColIndex="107" Width="100"></COLUMN>
    <COLUMN Name="VDD__min_" Caption="VDD &#40;min&#41;" Index="108" BandIndex="0" RowIndex="0" ColIndex="108" Width="100"></COLUMN>
    <COLUMN Name="VDD__typ_" Caption="VDD &#40;typ&#41;" Index="109" BandIndex="0" RowIndex="0" ColIndex="109" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW ADC_channels="" Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="2012&#91;0805&#93;" Code_JEDEC="" Code_JEITA="0805" Comment="C0805" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="Manufacturer Link" ComponentLink1URL="http://www.kemet.com/" ComponentLink2Description="Datasheet" ComponentLink2URL="http://www.kemet.com/kemet/web/homepage/kechome.nsf/vapubfilesname/F3102TA.pdf/&#36;file/F3102TA.pdf" ComponentLink3Description="" ComponentLink3URL="" ComponentLink4Description="" ComponentLink4URL="" CompType="" CurrentDate="2012-07-20" CurrentTime="19:28:47" DatasheetDocument="Mar-2001" DatasheetVersion="" Date="" Description="Ceramic Chip Capacitor - Standard" Designator="C1" Designator_X_Mil_="9290" Designator_X_mm_="235.966" Designator_Y_Mil_="5210" Designator_Y_mm_="132.334" DesignItemId="C0805" Document="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM.SchDoc" DocumentName="HIGROTERM.SchDoc" DocumentNumber="" DrawnBy="" DrillSize="" Engineer="" Flash="" fmax="" Footprint="0805" GPIOs="" Height_Mil_="0" Height_mm_="0" High_Reliability="" I2C="" ImagePath="" Index="1" ItemGUID="" LatestRevisionDate="19-Mar-2004" LatestRevisionNote="Silkscreen size reduced." Library_Name="KEMET Chip Capacitor.IntLib" Library_Reference="C0805" LibRef="C0805" LogicalDesignator="C1" Manufacturer="" Model_Footprint="Chip Capacitor; Body 2.0 x 1.2 mm &#40;LxW typ&#41;" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="2012-07-18" Note="Footprint corresponds to dimensions for bulk cassette packaging. This case size has tightened tolerances." Organization="" PackageDescription="" PackageDocument="Mar-2001" PackageReference="0805" PackageTopMarking="" PackageVersion="" PartNumber="" PartType="C0805" PCB3D="" PhysicalPath="HIGROTERM" PinCount="" Pins="2" PLL="" PowerWise="" Project="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM1.PrjPcb" ProjectName="HIGROTERM1.PrjPcb" Published="17-Jul-2002" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="2" Signal_Integrity="C0805" Simulation="CAP" SourceLibraryName="KEMET Chip Capacitor.IntLib" SPI="" SRAM="" Sub_Parts="1" Time="" Timers="" Title="" UART="" UniqueIdName="JTOISOJK" UniqueIdPath="" Value="100nF" Variant="" VaultGUID="" VDD__max_="" VDD__min_="" VDD__typ_=""></ROW>
    <ROW ADC_channels="" Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="2012&#91;0805&#93;" Code_JEDEC="" Code_JEITA="0805" Comment="0805" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="Manufacturer Link" ComponentLink1URL="http://www.kemet.com/" ComponentLink2Description="Datasheet" ComponentLink2URL="http://www.kemet.com/kemet/web/homepage/kechome.nsf/vapubfilesname/F3102TA.pdf/&#36;file/F3102TA.pdf" ComponentLink3Description="" ComponentLink3URL="" ComponentLink4Description="" ComponentLink4URL="" CompType="" CurrentDate="2012-07-20" CurrentTime="19:28:47" DatasheetDocument="Mar-2001" DatasheetVersion="" Date="" Description="Ceramic Chip Capacitor - Standard" Designator="C2" Designator_X_Mil_="9290" Designator_X_mm_="235.966" Designator_Y_Mil_="3910" Designator_Y_mm_="99.314" DesignItemId="C0805" Document="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM.SchDoc" DocumentName="HIGROTERM.SchDoc" DocumentNumber="" DrawnBy="" DrillSize="" Engineer="" Flash="" fmax="" Footprint="0805" GPIOs="" Height_Mil_="0" Height_mm_="0" High_Reliability="" I2C="" ImagePath="" Index="2" ItemGUID="" LatestRevisionDate="19-Mar-2004" LatestRevisionNote="Silkscreen size reduced." Library_Name="KEMET Chip Capacitor.IntLib" Library_Reference="C0805" LibRef="C0805" LogicalDesignator="C2" Manufacturer="" Model_Footprint="Chip Capacitor; Body 2.0 x 1.2 mm &#40;LxW typ&#41;" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="2012-07-18" Note="Footprint corresponds to dimensions for bulk cassette packaging. This case size has tightened tolerances." Organization="" PackageDescription="" PackageDocument="Mar-2001" PackageReference="0805" PackageTopMarking="" PackageVersion="" PartNumber="" PartType="0805" PCB3D="" PhysicalPath="HIGROTERM" PinCount="" Pins="2" PLL="" PowerWise="" Project="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM1.PrjPcb" ProjectName="HIGROTERM1.PrjPcb" Published="17-Jul-2002" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="2" Signal_Integrity="C0805" Simulation="CAP" SourceLibraryName="KEMET Chip Capacitor.IntLib" SPI="" SRAM="" Sub_Parts="1" Time="" Timers="" Title="" UART="" UniqueIdName="DNFPHDNB" UniqueIdPath="" Value="100nF" Variant="" VaultGUID="" VDD__max_="" VDD__min_="" VDD__typ_=""></ROW>
    <ROW ADC_channels="" Address1="" Address2="" Address3="" Address4="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="2012&#91;0805&#93;" Code_JEDEC="" Code_JEITA="0805" Comment="C0805" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="Manufacturer Link" ComponentLink1URL="http://www.kemet.com/" ComponentLink2Description="Datasheet" ComponentLink2URL="http://www.kemet.com/kemet/web/homepage/kechome.nsf/vapubfilesname/F3102TA.pdf/&#36;file/F3102TA.pdf" ComponentLink3Description="" ComponentLink3URL="" ComponentLink4Description="" ComponentLink4URL="" CompType="" CurrentDate="2012-07-20" CurrentTime="19:28:47" DatasheetDocument="Mar-2001" DatasheetVersion="" Date="" Description="Ceramic Chip Capacitor - Standard" Designator="C3" Designator_X_Mil_="8390" Designator_X_mm_="213.106" Designator_Y_Mil_="3690" Designator_Y_mm_="93.726" DesignItemId="C0805" Document="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM.SchDoc" DocumentName="HIGROTERM.SchDoc" DocumentNumber="" DrawnBy="" DrillSize="" Engineer="" Flash="" fmax="" Footprint="0805" GPIOs="" Height_Mil_="0" Height_mm_="0" High_Reliability="" I2C="" ImagePath="" Index="3" ItemGUID="" LatestRevisionDate="19-Mar-2004" LatestRevisionNote="Silkscreen size reduced." Library_Name="KEMET Chip Capacitor.IntLib" Library_Reference="C0805" LibRef="C0805" LogicalDesignator="C3" Manufacturer="" Model_Footprint="Chip Capacitor; Body 2.0 x 1.2 mm &#40;LxW typ&#41;" Model_Signal_Integrity="" Model_Simulation="Capacitor" Models="3" ModifiedDate="2012-07-18" Note="Footprint corresponds to dimensions for bulk cassette packaging. This case size has tightened tolerances." Organization="" PackageDescription="" PackageDocument="Mar-2001" PackageReference="0805" PackageTopMarking="" PackageVersion="" PartNumber="" PartType="C0805" PCB3D="" PhysicalPath="HIGROTERM" PinCount="" Pins="2" PLL="" PowerWise="" Project="C:&#92;Users&#92;pslupski&#92;Documents&#92;Projects&#92;HIGROTERM&#92;HIGROTERM1.PrjPcb" ProjectName="HIGROTERM1.PrjPcb" Published="17-Jul-2002" Publisher="Altium Limited" Quantity="1" Revision="" RevisionGUID="" RoHS="" Rule="" SheetNumber="" SheetTotal="2" Signal_Integrity="C0805" Simulation="CAP" SourceLibraryName="KEMET Chip Capacitor.IntLib" SPI="" SRAM="" Sub_Parts="1" Time="" Timers="" Title="" UART="" UniqueIdName="FMNRNHDQ" UniqueIdPath="" Value="100pF" Variant="" VaultGUID="" VDD__max_="" VDD__min_="" VDD__typ_=""></ROW>